version: '2'
services:
  # Use to build project
  doc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./content:/app/content:ro
      - ./static:/app/static:ro
      - ./gatsby-node.js:/app/gatsby-node.js:ro
      - ./gatsby-config.js:/app/gatsby-config.js:ro
      - ./config.js:/app/config.js:ro
      - ./tests:/app/tests:ro
    command: sleep 3600 # Use to let container up during build
