version: '3'
services:
  # Use to build project
  doc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./content:/app/content:ro
      - ./static:/app/static:ro
      - ./gatsby-node.js:/app/gatsby-node.js:ro
      - ./gatsby-config.js:/app/gatsby-config.js:ro
      - ./config.js:/app/config.js:ro
      - ./tests:/app/tests:ro
    command: sleep 3600 # Use to let container up during build
  # Used to run a server to be used by test
  server:
    image: python:3.5-stretch
    volumes:
      - ./public:/app/public:ro
    expose:
      - "8000"
    command: bash -c "cd /app/public && python -m http.server 8000"
  # Allow to run scrap tests before deployment
  test:
    build: tests
    volumes:
      - ./tests/src:/app/src:ro
      - ./tests/package.json:/app/package.json:ro
    links:
      - server
    command: yarn test
