version: '3'
services:
  # Use to build project
  doc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./src:/app/src
      - ./gatsby-node.js:/app/gatsby-node.js
      - ./gatsby-config.js:/app/gatsby-config.js
      - ./tests:/app/tests
    command: sleep 3600 # Use to let container up during build
  # Used to run a server to be used by test
  server:
    image: python:3.5-stretch
    volumes:
      - ./public:/app/public
    expose:
      - "8000"
    command: bash -c "cd /app/public && python -m http.server 8000"
  # Allow to run scrap tests before deployment
  test:
    build: tests
    volumes:
      - ./tests/src:/app/src
      - ./tests/package.json:/app/package.json
    links:
      - server
    command: yarn test
