version: '3'
services:
  doc:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./gatsby-node.js:/app/gatsby-node.js:ro
      - ./gatsby-config.js:/app/gatsby-config.js:ro
      - ./public/diagrams:/app/public/diagrams
      - ./public:/app/public
