---
- hosts: all
  tasks:
    - name: Prepare config.js with Algolia ids
      copy:
        content: |
          module.exports = {
            githubToken: '',
            algolia: {
              appId: '{{ algolia.appId }}',
              publicKey: '{{ algolia.publicKey }}',
              apiKey: '{{ algolia.apiKey }}',
            },
          };
        dest: "{{ zuul.project.src_dir }}/config.js"

    - name: configure path prefix
      lineinfile:
        line: "pathPrefix: '/logs/{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}/public',"
        insertafter: "module.exports = {"
        path: "{{ zuul.project.src_dir }}/gatsby-config.js"
        state: present

    - name: make
      command: "make"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: make build
      command: "make build"
      args:
        chdir: "{{ zuul.project.src_dir }}"

    - name: Upload site
      synchronize:
        src: '{{ zuul.project.src_dir }}/public'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --prune-empty-dirs
