---
- hosts: all
  tasks:
    - name: Prepare config.js with Algolia ids
      copy:
        content: |
          module.exports = {
            githubToken: '',
            algolia: {
              appId: '{{ algolia.appId }}',
              publicKey: '{{ algolia.publicKey }}',
              apiKey: '{{ algolia.apiKey }}',
            },
          };
        dest: '{{ zuul.project.src_dir }}/config.js'

    - name: make
      command: 'make'
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: make build
      command: 'make build'
      args:
        chdir: '{{ zuul.project.src_dir }}'

    # The matching public key was added manually to zuul-publisher@wazo-platform.org:.ssh/authorized_keys
    # command="/usr/local/bin/rrsync -wo /var/www/wazo-platform" ssh-ed25519 AAAAC... zuul
    - name: Set up publication private key from Zuul's secret
      copy:
        content: '{{ publication.private_key }}'
        dest: '{{ ansible_user_dir }}/.ssh/id_ed25519'
        mode: '0400'

    - name: Upload site
      command: 'rsync -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" -av --delete {{ zuul.project.src_dir }}/public/ zuul-publisher@webserver.wazo.community:'
